embed_dim: 1536
loss: weighted absolute temp-std squared geometric l2
channel_weights: auto
depth: 12
drop_path_rate: 0.1
data_loader_config: pytorch # was dali
add_zenith: true
add_orography: true
add_landmask: true
residual: true
log_to_wandb: false
batch_size: 1 # 64
in_channels:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
- 13
- 14
- 15
- 16
- 17
- 18
- 19
- 20
- 21
- 22
- 23
- 24
- 25
- 26
- 27
- 28
- 29
- 30
- 31
- 32
- 33
- 34
- 35
- 36
- 37
- 38
- 39
- 40
- 41
- 42
- 43
- 44
- 45
- 46
- 47
- 48
- 49
- 50
- 51
- 52
- 53
- 54
- 55
- 56
- 57
- 58
- 59
- 60
- 61
- 62
- 63
- 64
- 65
- 66
- 67
- 68
- 69
- 70
- 71
- 72
out_channels:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
- 13
- 14
- 15
- 16
- 17
- 18
- 19
- 20
- 21
- 22
- 23
- 24
- 25
- 26
- 27
- 28
- 29
- 30
- 31
- 32
- 33
- 34
- 35
- 36
- 37
- 38
- 39
- 40
- 41
- 42
- 43
- 44
- 45
- 46
- 47
- 48
- 49
- 50
- 51
- 52
- 53
- 54
- 55
- 56
- 57
- 58
- 59
- 60
- 61
- 62
- 63
- 64
- 65
- 66
- 67
- 68
- 69
- 70
- 71
- 72
train_data_path: data/train
valid_data_path: data/test
inf_data_path: data/out_of_sample
time_means_path: data/stats/time_means.npy
global_means_path: data/stats/global_means.npy
global_stds_path: data/stats/global_stds.npy
time_diff_means_path: data/stats/time_diff_means.npy
time_diff_stds_path: data/stats/time_diff_stds.npy
orography_path: data/stats/orography.npy
landmask_path: data/stats/land_sea_cache.npy
track_channels: [u10m, v10m, t2m, tcwv]
channel_names:
- u10m
- v10m
- u100m
- v100m
- t2m
- sp
- msl
- tcwv
- u50
- u100
- u150
- u200
- u250
- u300
- u400
- u500
- u600
- u700
- u850
- u925
- u1000
- v50
- v100
- v150
- v200
- v250
- v300
- v400
- v500
- v600
- v700
- v850
- v925
- v1000
- z50
- z100
- z150
- z200
- z250
- z300
- z400
- z500
- z600
- z700
- z850
- z925
- z1000
- t50
- t100
- t150
- t200
- t250
- t300
- t400
- t500
- t600
- t700
- t850
- t925
- t1000
- q50
- q100
- q150
- q200
- q250
- q300
- q400
- q500
- q600
- q700
- q850
- q925
- q1000

nettype: swin
patch_size: 4
window_ratio: 80
num_heads: 8
full_pos_embed: true
rel_pos: false
mlp_ratio: 4
activation_ckpt: false
activation_ckpt_idx: 0
checkpointing: false
log_to_screen: true
save_checkpoint: true
project: ERA5_swin
entity: weatherbenching
optimizer_type: adam
scheduler: CosineAnnealingLR
max_epochs: 70
lr: 1E-3
num_data_workers: 1 # 8
n_future: 0
finetune: false
dt: 1
img_size: [720, 1440]
exp_dir: experiments
model_grid_type: equiangular
enable_amp: true
name: swin_73var_geo_depth12_chweight_invar_e1536_00
group: swin_73var_geo_depth12_chweight_invar_e1536
data_num_shards: 1 # 64
data_shard_id: 0
n_in_channels: 73
n_out_channels: 73
experiment_dir: 
  experiments
checkpoint_path: 
  experiments/training_checkpoints/ckpt.tar
best_checkpoint_path: 
  experiments/training_checkpoints/best_ckpt.tar
resuming: true
global_batch_size: 1 # 64
local_batch_size: 1
img_shape_x: 720
img_shape_y: 1440